name: 6003esc
channels:
  - conda-forge
#  - r
dependencies:
  - r-pak
  - r-irkernel
#  - r-irkernel=1.1
#  - r-base=3.6.1
  - r-base
  - r-devtools
#  - r-remotes
  - r-tidyverse
  - r-pacman
  - r-shiny
  - r-rmarkdown
  - r-bookdown
  - r-ggpubr
 # - r-gtsummary
 # - r-rcpp
  - r-paletteer
  - r-learnr
  - r-scales
#  - r-captioner
#  - r-here
  - r-htmltools
  - r-agricolae
  - r-car
  - r-MASS
  - r-plotly
  - r-lubridate
  - r-patchwork
  - r-visdat
  - r-pastecs
  - r-rmisc
  - r-esquisse
  # - r-fontawesome
  - pandoc
 # - libgcc
